---
name: bank_sha
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies:
  another_flushbar: ^1.10.29
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^6.0.0
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins_Regular.ttf


flutter_icons:
  android: true
  ios: true
  image_path: "assets/img_logo.png"